fix: Add zlib as run requirement
* While zlib isn't formally required for things to run if there is already
  a C++ compiler on the target machine, if cxx-compiler is installed in
  the same environment (which is a common pattern for C++ projects) compilation
  will fail with

  <Pythia8 prefix directory>/include/Pythia8/Streams.h:23:10: fatal error: zlib.h: No such file or directory

  To guard against this, include zlib as a run requirement, which, while
  possibly redundant, should make things easier for the end user and should not
  impose any requirement conflicts either.
* Remove zlib as an additional test environment requirement.
* Add main01 example to tests as the simplest check of zlib.
* Bump build number.